include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - firestore-tests/**
    - "22100011044*/**"

linter:
  rules:
    always_declare_return_types: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    use_super_parameters: true
